# fly.toml app configuration file generated for backend-proud-haze-8547 on 2025-12-03T15:43:40+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-proud-haze-8547'
primary_region = 'sin'

[build]

[deploy]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1   # <= important for persistent socket connections

  # Required so Fly.io doesn't kill WebSocket connections
  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
