"use client";

import Link from "next/link";
import { ArrowLeft, FileText, ChevronRight, ScrollText } from "lucide-react";

interface PolicySection {
  id: string;
  title: string;
  content: React.ReactNode;
}

const POLICY_SECTIONS: PolicySection[] = [
  {
    id: "introduction",
    title: "Introduction",
    content: (
      <>
        <p className="mb-4">
          SimTrading is a personal, educational project that simulates stock trading
            on Indian markets (NSE/BSE). It is a portfolio/demo application built to
            practice full-stack development — not a financial product.
        </p>
        <p>
          Please read these terms carefully before using our services. If you do not
          agree with any part of these terms, you must not use our platform.
        </p>
      </>
    ),
  },
  {
    id: "eligibility",
    title: "Eligibility",
    content: (
      <>
        <p className="mb-4">
          You must be at least 18 years old to use TradeSim. By using our platform,
          you represent and warrant that you are of legal age and have the capacity
          to enter into a binding agreement.
        </p>
        <p>
          TradeSim is intended for educational and simulation purposes only. No
          real financial transactions are executed through this platform.
        </p>
      </>
    ),
  },
  {
    id: "account",
    title: "Account & Security",
    content: (
      <>
        <p className="mb-4">
          You are responsible for maintaining the confidentiality of your account
          credentials and for all activities that occur under your account.
        </p>
        <ul className="list-disc pl-5 space-y-2 mb-4">
          <li>Use a strong, unique password for your account.</li>
          <li>Notify us immediately of any unauthorized access.</li>
        </ul>
        <p>
          We reserve the right to suspend or terminate accounts that violate these
          terms or engage in fraudulent activity.
        </p>
      </>
    ),
  },
  {
    id: "simulation",
    title: "Trading Simulation",
    content: (
      <>
        <p className="mb-4">
          **Not real trading.** All money, prices, and trades are simulated.
            No real currency changes hands.
        </p>
        <p className="mb-4">
          **Not financial advice.** Nothing in this app constitutes investment
            advice, a recommendation, or a solicitation to trade real securities.
        </p>
        <p>
          **Not real market data.** Prices are generated by a simulated price
            engine (mean-reversion model) and do not reflect actual NSE/BSE prices.
        </p>
        <p>
            **Not affiliated** with NSE, BSE, SEBI, or any registered broker/exchange.
        </p>
      </>
    ),
  },
  {
    id: "privacy",
    title: "Privacy & Data",
    content: (
      <>
        <p className="mb-4">
          We store your email, trade history, and portfolio state to make the app
  function (via Supabase Auth + PostgreSQL).
        </p>
        <p>
         We don&apos;t sell or share your data with third parties.
        </p>
        <p>
            You can request account deletion by emailing [your email].
        </p>
      </>
    ),
  },
  {
    id: "liability",
    title: "Limitation of Liability",
    content: (
      <>
        <p className="mb-4">
          This app is provided &quot;as is&quot; built and maintained by a single developer
            as a demo project. Uptime, data persistence, and accuracy are not
            guaranteed. Don&apos;t rely on it for anything beyond learning/demonstration.
        </p>
      </>
    ),
  },
  {
    id: "changes",
    title: "Changes to Terms",
    content: (
      <>
        <p className="mb-4">
          We may update these terms from time to time. We will notify you of any
          material changes via email or through the platform.
        </p>
        <p>
          Continued use of TradeSim after changes constitutes acceptance of the
          revised terms.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    title: "Contact Us",
    content: (
      <>
        <p className="mb-4">
          If you have any questions about these terms, please contact us at:
        </p>
        <div
          className="p-4 rounded-lg border"
          style={{
            backgroundColor: "var(--color-bg)",
            borderColor: "var(--color-border)",
          }}
        >
          <p className="text-sm font-medium" style={{ color: "var(--color-text)" }}>
            Divyansh Gupta
          </p>
          <p className="text-sm" style={{ color: "var(--color-text-secondary)" }}>
            [divyanshg556@gmail.com]
          </p>
        </div>
      </>
    ),
  },
];

export default function PolicyPage() {
  const lastUpdated = "July 3, 2026";

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const offset = 80;
      const top = element.getBoundingClientRect().top + window.scrollY - offset;
      window.scrollTo({ top, behavior: "smooth" });
    }
  };

  return (
    <div className="min-h-screen" style={{ backgroundColor: "var(--color-bg)" }}>
      {/* Header */}
      <header
        className="sticky top-0 z-30 border-b"
        style={{
          backgroundColor: "var(--color-bg-surface)",
          borderColor: "var(--color-border)",
        }}
      >
        <div className="max-w-5xl mx-auto px-4 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link
              href="/dashboard"
              className="p-2 -ml-2 rounded-lg transition-colors duration-150"
              style={{ color: "var(--color-text-secondary)" }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = "var(--color-bg-elevated)";
                e.currentTarget.style.color = "var(--color-text)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = "transparent";
                e.currentTarget.style.color = "var(--color-text-secondary)";
              }}
            >
              <ArrowLeft className="w-5 h-5" />
            </Link>

            <div className="flex items-center gap-2">
              <ScrollText
                className="w-5 h-5"
                style={{ color: "var(--color-text-secondary)" }}
              />
              <h1
                className="text-base font-semibold"
                style={{ color: "var(--color-text)" }}
              >
                Terms of Service
              </h1>
            </div>
          </div>

          <span
            className="text-xs font-medium hidden sm:block"
            style={{ color: "var(--color-text-secondary)" }}
          >
            Last updated {lastUpdated}
          </span>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-8 sm:py-12">
        <div className="flex flex-col lg:flex-row gap-8 lg:gap-12">
          {/* Sidebar — Table of Contents */}
          <aside className="lg:w-64 shrink-0">
            <div className="lg:sticky lg:top-24">
              <div
                className="hidden lg:flex items-center gap-2 mb-4 px-3 py-2 rounded-lg"
                style={{
                  backgroundColor: "var(--color-bg-elevated)",
                  color: "var(--color-text-secondary)",
                }}
              >
                <FileText className="w-4 h-4" />
                <span className="text-xs font-semibold uppercase tracking-wider">
                  Contents
                </span>
              </div>

              <nav className="flex lg:flex-col gap-1 overflow-x-auto lg:overflow-visible pb-2 lg:pb-0 -mx-4 px-4 lg:mx-0 lg:px-0">
                {POLICY_SECTIONS.map((section) => (
                  <button
                    key={section.id}
                    onClick={() => scrollToSection(section.id)}
                    className="group flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-all duration-150 whitespace-nowrap lg:whitespace-normal text-left"
                    style={{
                      color: "var(--color-text-secondary)",
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.backgroundColor = "var(--color-bg-elevated)";
                      e.currentTarget.style.color = "var(--color-text)";
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.backgroundColor = "transparent";
                      e.currentTarget.style.color = "var(--color-text-secondary)";
                    }}
                  >
                    <ChevronRight className="w-3.5 h-3.5 opacity-0 lg:group-hover:opacity-100 transition-opacity duration-150 shrink-0" />
                    <span>{section.title}</span>
                  </button>
                ))}
              </nav>

            </div>
          </aside>

          {/* Main Content */}
          <div className="flex-1 min-w-0">
            {/* Mobile Meta */}
            <div className="mb-8 sm:mb-10 lg:hidden">
              <span
                className="text-xs font-medium"
                style={{ color: "var(--color-text-secondary)" }}
              >
                Last updated {lastUpdated}
              </span>
            </div>

            {/* Title Block */}
            <div className="mb-10 sm:mb-12">
              <h2
                className="text-2xl sm:text-3xl font-bold mb-3"
                style={{ color: "var(--color-text)" }}
              >
                Terms of Service
              </h2>
              <p
                className="text-sm sm:text-base leading-relaxed"
                style={{ color: "var(--color-text-secondary)" }}
              >
                Please read these terms carefully before using TradeSim. These terms
                govern your access to and use of our trading simulation platform.
              </p>
            </div>

            {/* Sections */}
            <div className="space-y-10 sm:space-y-12">
              {POLICY_SECTIONS.map((section, index) => (
                <section
                  key={section.id}
                  id={section.id}
                  className="scroll-mt-24"
                >
                  <div className="flex items-center gap-3 mb-4">
                    <span
                      className="flex items-center justify-center w-6 h-6 rounded-md text-xs font-bold shrink-0"
                      style={{
                        backgroundColor: "var(--color-bg-elevated)",
                        color: "var(--color-text-secondary)",
                      }}
                    >
                      {index + 1}
                    </span>
                    <h3
                      className="text-lg sm:text-xl font-semibold"
                      style={{ color: "var(--color-text)" }}
                    >
                      {section.title}
                    </h3>
                  </div>

                  <div
                    className="pl-9 text-sm sm:text-base leading-relaxed"
                    style={{ color: "var(--color-text-secondary)" }}
                  >
                    {section.content}
                  </div>
                </section>
              ))}
            </div>

            {/* Footer Divider */}
            <div
              className="mt-12 sm:mt-16 pt-8 border-t"
              style={{ borderColor: "var(--color-border)" }}
            >
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <p
                  className="text-xs"
                  style={{ color: "var(--color-text-secondary)" }}
                >
                  © 2026 TradeSim. All rights reserved.
                </p>
                <div className="flex items-center gap-4">
                  <Link
                    href="/privacy"
                    className="text-xs font-medium transition-colors duration-150 hover:underline underline-offset-2"
                    style={{ color: "var(--color-text-secondary)" }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.color = "var(--color-brand)";
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.color = "var(--color-text-secondary)";
                    }}
                  >
                    Privacy Policy
                  </Link>
                  <Link
                    href="/cookies"
                    className="text-xs font-medium transition-colors duration-150 hover:underline underline-offset-2"
                    style={{ color: "var(--color-text-secondary)" }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.color = "var(--color-brand)";
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.color = "var(--color-text-secondary)";
                    }}
                  >
                    Cookie Policy
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}