-- AlterTable
ALTER TABLE "public"."Transaction" ADD COLUMN     "realizedPnl" DECIMAL(65,30) NOT NULL DEFAULT 0,
ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30);
